plugin: google.cloud.gcp_compute
zones:
  - europe-west1-b
projects:
  - "{{ project_id }}" # replace with your qwiklabs project ID
filters:
  - status = RUNNING
  - scheduling.automaticRestart = true AND status = RUNNING
auth_kind: application
scopes:
  - 'https://www.googleapis.com/auth/cloud-platform'
  - 'https://www.googleapis.com/auth/compute.readonly'
keyed_groups:
  - prefix: gcp
    key: labels
name_suffix: .qa.com
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP